variables:
    PUBLIC_TAG: 'strm/arduino-temperature'
stages:
    - test
    - build

test-backend:
    stage: test
    script:
        - cd backend
        - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-' | sed 's/master/latest/g')
        - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG"-test -f ./tests/Dockerfile .
        - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
        - docker tag "$CI_REGISTRY_IMAGE:$IMAGE_TAG" "$PUBLIC_TAG"
        - docker run --rm  "$CI_REGISTRY_IMAGE:$IMAGE_TAG"-test
    tags:
        - docker

build-backend:
  stage: build
  script:
    - cd backend
    - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-' | sed 's/master/latest/g')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    - docker tag "$CI_REGISTRY_IMAGE:$IMAGE_TAG" "$PUBLIC_TAG"
  tags:
    - docker
